name: ovs-configuration.service
dropins:
- name: 10-dpu-pfrep.conf
  contents: |
    [Service]
    ExecStartPre=/usr/local/bin/ovs-reconfig.sh
    ExecStartPost=/usr/local/bin/ovs-add-pf.sh {{.PfRepName}}
