mode: 0755
overwrite: true
path: "/usr/local/bin/configure-switchdev.sh"
contents:
  inline: |
    #!/bin/bash
    set -eux

    # Source the common DPU functions and variables script.
    . /usr/local/bin/common-dpu.sh

    for interface in /sys/class/net/*; do
      if [[ -d $interface ]] && [[ -d $interface/device ]]; then
        if ! vendor_id=$(<"$interface/device/vendor"); then
          continue
        fi
        if ! device_id=$(<"$interface/device/device"); then
          continue
        fi
        interface_name=$(basename "$interface")
        if is_nvidia_bluefield_dpu "$vendor_id" "$device_id" "$interface_name"; then
          pci_address=$(readlink -f "$interface"/device | awk -F '/' '{print $(NF)}')
          echo "NVIDIA BF DPU: Setting $interface_name at pci/$pci_address to switchdev mode"
          devlink dev eswitch set pci/${pci_address} mode switchdev
        fi
      fi
    done

    exit 0
