mode: 0755
overwrite: true
path: "/usr/local/bin/ovs-reconfig.sh"
contents:
  inline: |
    #!/bin/bash
    set -eux

    if [ -f /etc/NetworkManager/systemConnectionsMerged/ovs-if-phys0.nmconnection ] && grep -q interface-name=p0 /etc/NetworkManager/systemConnectionsMerged/ovs-if-phys0.nmconnection
    then
      echo "br-ex is ready, no need to be reconfigured."
    else
      echo "br-ex is not set up with switchdev port, need to be rebuilt."
      /usr/local/bin/configure-ovs.sh OpenShiftSDN || true
    fi
